- package-lock.json
- package.json
- src/components/AdminIndex.js
- src/components/AdminLogin.js
- src/components/AdminPage.js
- src/components/AdminRoute.js
- src/components/Loading.js
- src/components/MapPage.js
react-firebase-hooks API changed to using arrays in v2 which was release recently. Updated that dep and the usage
> Update firebase hooks

- src/components/JobList.js
- src/components/JobsFilter.js
- src/components/JobsPage.js
Adds filtering by job type (full-time or part-time) functionality to the job filter panel.
> Added job type filter functionality

- package.json
- src/components/AboutPage.js
- src/components/CompaniesPage.js
- src/components/CompanyPage.js
- src/components/HomePage.js
- src/components/JobPage.js
- src/components/JobsPage.js
- src/components/NewToGainesvillePage.js
- yarn.lock
This uses `react-helmet` to dynamically modify title, meta, and graph tags in the document head. Only publicly viewable pages were modified.
Note: This dynamically modify's tags at runtime. If search engine's aren't loading a lot of JS then Helmet may not get a chance to run. This may need to be tested further.
Additionally, the SEO content added for title's and descriptions was best-effort. I am no SEO expert, and some of the content can probably be more optimized.
> Added relevant tags to individual page heads for SEO

- src/components/JobList.js
- src/components/JobsFilter.js
This adds the search filter to take available company names into consideration when filtering jobs in addition to just jobs names.
> Added company name for job search results

- firebase.json
- functions/.gitignore
- functions/package-lock.json
- functions/package.json
- functions/src/index.ts
- functions/tsconfig.json
This adds a Firebase function to listen for any new documents added to the `addCompanyResponses` collection in Firestore, and sends an email via SendGrid with the documents data to `lauren@startupgnv.com`. Note, the `from` address is currently `will@startupgnv.com`. The api key for SendGrid is currently stored in the Firebase function config and safely private. Firebase functions can be deployed independently or along with the web app in the case of a production release.
> Added company resource email function

- functions/src/index.ts
- src/components/AddCompanyPage.js
This adds a 'Company URL' field to the Add Company form. This includes updating the email function to have the url field included in notification emails to Lauren as well.
> Added Company URL field to contact form

- src/components/Admin/Company/Photos.js
- src/components/AdminEditCompanyPage.js
- src/components/Company/Gallery.js
- src/components/CompanyPage.js
- storage.rules
This adds a gallery to a companies page if they have added photos via the admin dashboard. Both adding and deleting photos can be handled via the admin page. If company does not yet have any photos uploaded, the gallery will not appear.
Note: Adding more than 4-5 photos at a time may cause errors, due to hitting the Firebase upload size limit for a single request. This can be mitigated if photos are added in small batches, but it is something to be aware of.
> Added gallery to company page & admin page

- package.json
- src/components/Admin/Settings/CategoryForm.js
- src/components/Admin/Settings/Expandable.js
- src/components/Admin/Settings/IndustryForm.js
- src/components/Admin/Settings/Input.js
- src/components/Admin/Settings/InputWithRadio.js
- src/components/Admin/Settings/index.js
- src/components/AdminJobForm.js
- src/components/AdminPage.js
- yarn.lock
This adds a couple features:
1. This changes the category selection field in the job editing page of the admin portal from a list of checkboxes to an autocomplete list with chips for each selected category.
2. This adds 2 new fields to the settings page. First, an input for adding industries that will appear in the company industries list, as well as a list of chips to delete existing industries. Second, is an input/radio selector for adding categories to the job categories list, as well as a list of chips to delete existing categories.
Note: This does not include testing for potential errors if an existing category or industry is deleted that a company or job requires.
> Added category editing & updated category selector

- functions/package-lock.json
- functions/package.json
- functions/src/addNewsletterSubscriber.ts
- functions/src/emailCompanyResponse.ts
- functions/src/index.ts
- public/index.html
- src/components/Footer/NewletterForm.js
- src/firebase.js
This adds a Firebase function to create new subscribers in Mailchimp when called with the provided email as payload.
For security purposes, Mailchimp does not allow accessing its API via CORS, so this request must be made through a function. 
The Audience ID & API Key are securely kept private as environment variables in Firebase passed at runtime.
> Connected Mailchimp to subscriber signup in footer

- src/components/Footer/Footer.js
This updates/adds the following content to the footer:
> startGNV is a 501(c)(3) non-profit dedicated to growing the innovation ecosystem of Greater Gainesville.
> This website was only possible thanks to contributions from The University of Florida, The Greater Gainesville Chamber of Commerce and The City of Gainesville.
> Updated footer content

- src/components/Companies/CompaniesFilter.js
- src/components/Companies/CompaniesList.js
- src/components/Jobs/JobList.js
- src/components/Jobs/JobsFilter.js
- src/components/Jobs/JobsPage.js
- src/components/UI/Filter.js
This adds a small, realtime counter to the amount of jobs or companies displayed on their respective pages, and updates based on the active filters.
> Added counter to companies/jobs filter

- src/components/AboutPage.js
- src/components/HomePage.js
This update's content/font sizing on the home page, and removes some unnecessary copy from the mission section of the about page.
> Updated home/about page copy

- package.json
- src/assets/images/x.svg
- src/components/Site/Footer/Footer.js
- src/components/Site/Home/HomePage.js
- src/components/Site/Home/NewletterPopup.js
- yarn.lock
This adds a thin newsletter form that will slide up when the user is scrolling up (but not down) the screen. Additionally, the form will only be active when on the home screen and when the footer is not within view (per Laurens requests).
Note 1: I bumped `react-router-dom` 1 minor version since it includes a convenient `useLocation` hook for fetching the current route.
Note 2: Make sure to test that emails are actually being submitted to MailChimp. The submit button calls the exact same email logic as the one in the footer so I don't anticipate any issues, but I would check just in case.
> Added Newsletter slider popup to home screen

- src/components/Admin/Companies/CompaniesPage.js
- src/components/Admin/Company/EditPage.js
This adds a "Save As Draft" submit option when creating or editing a company.
Companies submitted as drafts have their draft version stored in a separate `companyDrafts` collection in Firebase. This allows drafts to be viewable in the admin client but not the frontend. When a company is then "Published", the drafted document is copied over to the `companies` collection, and the draft document is deleted.
> Added Save As Draft option for companies

- src/components/Admin/Company/EditPage.js
- src/components/Site/Company/CompanyPage.js
- src/components/Site/Company/Instagram.js
- src/components/Site/Company/instagram-api.js
This adds a custom Instagram feed below a companies personal gallery. It includes up to the 3 most recent posts made by an associated account (or fewer if a page has less than 3 posts total).
This also adds an option in the company edit page to input an Instagram username through the admin portal.
> Added instagram feed to company pages

- src/components/Site/Jobs/JobList.js
- src/components/Site/Jobs/JobsFilter.js
- src/components/Site/Jobs/JobsPage.js
This adds an additional search function to allow for filtering jobs by their category name.
> Added job searching by category

- src/components/Admin/Company/EditPage.js
- src/components/Admin/Job/EditPage.js
- src/components/Admin/Settings/CategoryForm.js
- src/components/App.js
- src/components/Site/Blog/Catalog.js
- src/components/Site/Blog/api.js
- src/components/Site/Home/HomePage.js
This adds a blog catalog page at `/blog` that can be accessed via the new "View All" link on the home page.
This also fixes a small bug where the company page was stuck loading forever on the admin portal when creating a new company.
> Added blog catalog page

- src/components/Admin/Companies/CompaniesPage.js
- src/components/Admin/Companies/ListCard.js
This adds badge indicators next to company logo's in the admin portal to indicate which companies are published vs which are currently only saved as drafts.
> Added draft badge to companies in admin portal

- src/components/Admin/Job/DisplayPage.js
- src/components/Admin/Job/EditPage.js
- src/components/Admin/Jobs/JobsPage.js
This adds the ability to save jobs as drafts similar to how it is currently done with companies.
This also includes an indicator to determine which jobs are drafts vs published, rather than separating that functionality out into a separate task like with companies.
> Added draft status to job posts

- src/components/Site/Companies/CompaniesFilter.js
- src/components/Site/Companies/CompaniesPage.js
This adds a search filter to the companies page, identical to the one that currently exists on the jobs page, allowing a user to search for companies by name.
> Added searching by company name

- src/components/Admin/Job/EditPage.js
This fixes an infinite loading issue that occurred when creating a completely new job in the admin portal.
> Fixed infinite loader when creating new job

- src/components/Site/Job/RequestJobPage.js
This adds responsive resizing to form elements on the job request page, allowing it to function normally on tablet and mobile screens.
> Added responsiveness to job request form

- src/components/Site/Footer/Footer.js
This updates the contact email in the footer of the page:
`info@startupgnv.com` => `team@startgnv.com`
> Updated contact email

- src/components/Admin/Job/EditPage.js
This fixes and tweaks a handful of miscellaneous issues related to the job request flow:
1. Requires a user to verify a company before the job can be published
2. Fixes an issue with unpublished jobs not being removed from the unpublished list after being published
3. Adds an field for company contact info to the job edit page
> Fixed various job request flow issues

- src/components/Admin/Companies/CompaniesPage.js
- src/components/Admin/Company/EditPage.js
- src/components/Admin/Company/Form.js
- src/components/Admin/Jobs/JobsPage.js
- src/components/Site/Companies/CompaniesFilter.js
- src/components/Site/Companies/CompaniesList.js
- src/components/Site/Companies/CompaniesPage.js
- src/components/Site/Company/AddCompanyPage.js
- src/components/Site/Company/NewCompanyForm.js
- src/components/Site/Job/RequestJobPage.js
- src/components/Site/Jobs/JobsFilter.js
- src/components/Site/UI/Form/Field.js
- src/components/Site/UI/Form/FieldRow.js
- src/components/Site/UI/RequestButton.js
- src/components/Site/UI/validation/ValidatorInput.js
This updates the job request page to also include a toggle-able section for adding company information, which will then be turned into a new company request. This also updates the existing `add-company` page to create a new company request in addition to notifying Lauren by email.
> Added company request flow

- src/components/Site/Job/RequestJobPage.js
This updates the copy on the Job Requests page, per Lauren's specifications.
> Updated copy on job request page

- src/components/Site/Footer/Footer.js
Added info needed to verify our company on facebook
> fixed footer info for facebook verification

- src/components/Site/Jobs/JobList.js
> temporary fix to get startGNV site back up

- pages/jobs/index.js
- src/components/Admin/Jobs/EditJob.js
- src/components/Site/Jobs/JobList.js
- src/components/Site/Jobs/JobsFilter.js
Added the required values to type filter
Added experience filter
Ability to add categories is in settings portion of admin page (did not add categories specified in user story needs to be done using the feature when it is pushed to live site)
> Added Filter options to Job Page

- pages/board-member-application.js
Update the form link on board app page, some formatting came along too
> Update board member app form with 2023 form

- pages/about.js
Per Tammy's updated list, clean up the about page to reflect current sponsors.
> Update active sponsors

- pages/index.js
- src/components/Banner.jsx
- src/components/utils/theme.js
Add a Banner component
Add battle of the bands "buy tickets" banner, hide it after August 20th 2023 (event is the 18th, but keep it up a lil longer in case someone for whatever reason wants to find the link a few days later)
> Add battle of the bands banner

- pages/about.js
tammy left to work for UF months lol, and we haven't done the founders dinner since way before I joined lol
> Cleanup, remove tammy from about

- pages/index.js
Was already hidden post event by super advanced technology
Now it no longer needs to be in the source
> remove battle of the bands banner
